import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { ContentNavbar } from "./ContentNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background antialiased font-mono")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="flex py-2 px-4 ">
            <div className="w-4/5"></div>
            <div className="w-1/5 flex justify-end gap-x-3">
              <ThemeToggle />
            </div>
          </nav>

          <main className="flex min-h-screen flex-col gap-y-4 items-center justify-start p-6 sm:p-8 ">
            <ContentNavbar />

            <div className="lg:w-1/2 w-full  flex flex-col justify-start items-center gap-y-4">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
